// <auto-generated />
using System;
using Ameriolize_Aegis.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ameriolize_Aegis.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211009115930_Added EndTime On LessonPlan")]
    partial class AddedEndTimeOnLessonPlan
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ameriolize_Aegis.Models.Attendance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("PupilId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PupilId");

                    b.HasIndex("TeacherId");

                    b.ToTable("PupilAttendance");
                });

            modelBuilder.Entity("Ameriolize_Aegis.Models.Centre", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Centres");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AddressLine1 = "123 John Newton SW",
                            AddressLine2 = "Newton Park",
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 27, DateTimeKind.Local).AddTicks(6739),
                            Name = "Kabega"
                        },
                        new
                        {
                            Id = 2L,
                            AddressLine1 = "237 John Newton SW",
                            AddressLine2 = "New Brighton",
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 29, DateTimeKind.Local).AddTicks(8985),
                            Name = "Sol Futi"
                        },
                        new
                        {
                            Id = 3L,
                            AddressLine1 = "123 John Newton SW",
                            AddressLine2 = "Newton Park",
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 29, DateTimeKind.Local).AddTicks(9063),
                            Name = "Daku"
                        });
                });

            modelBuilder.Entity("Ameriolize_Aegis.Models.LessonPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("LessonPlans");
                });

            modelBuilder.Entity("Ameriolize_Aegis.Models.Parent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CentreId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CentreId");

                    b.ToTable("Parents");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CentreId = 1L,
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 31, DateTimeKind.Local).AddTicks(3232),
                            DoB = new DateTime(1994, 10, 9, 13, 59, 30, 31, DateTimeKind.Local).AddTicks(4961),
                            FirstName = "Jane",
                            LastName = "Pope"
                        },
                        new
                        {
                            Id = 2L,
                            CentreId = 2L,
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 31, DateTimeKind.Local).AddTicks(5946),
                            DoB = new DateTime(1988, 10, 9, 13, 59, 30, 31, DateTimeKind.Local).AddTicks(6003),
                            FirstName = "Thembeka",
                            LastName = "Qweba"
                        },
                        new
                        {
                            Id = 3L,
                            CentreId = 3L,
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 31, DateTimeKind.Local).AddTicks(6039),
                            DoB = new DateTime(1976, 10, 9, 13, 59, 30, 31, DateTimeKind.Local).AddTicks(6041),
                            FirstName = "Jane",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 4L,
                            CentreId = 2L,
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 31, DateTimeKind.Local).AddTicks(6044),
                            DoB = new DateTime(1967, 10, 9, 13, 59, 30, 31, DateTimeKind.Local).AddTicks(6046),
                            FirstName = "Jon",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 5L,
                            CentreId = 1L,
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 31, DateTimeKind.Local).AddTicks(6048),
                            DoB = new DateTime(1992, 10, 9, 13, 59, 30, 31, DateTimeKind.Local).AddTicks(6049),
                            FirstName = "Joshua",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 6L,
                            CentreId = 3L,
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 31, DateTimeKind.Local).AddTicks(6051),
                            DoB = new DateTime(1972, 10, 9, 13, 59, 30, 31, DateTimeKind.Local).AddTicks(6053),
                            FirstName = "Thandi",
                            LastName = "Newton"
                        },
                        new
                        {
                            Id = 7L,
                            CentreId = 2L,
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 31, DateTimeKind.Local).AddTicks(6055),
                            DoB = new DateTime(1996, 10, 9, 13, 59, 30, 31, DateTimeKind.Local).AddTicks(6056),
                            FirstName = "Amanda",
                            LastName = "Qweba"
                        },
                        new
                        {
                            Id = 8L,
                            CentreId = 3L,
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 31, DateTimeKind.Local).AddTicks(6058),
                            DoB = new DateTime(2000, 10, 9, 13, 59, 30, 31, DateTimeKind.Local).AddTicks(6059),
                            FirstName = "Amyoli",
                            LastName = "Soze"
                        },
                        new
                        {
                            Id = 9L,
                            CentreId = 1L,
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 31, DateTimeKind.Local).AddTicks(6062),
                            DoB = new DateTime(1991, 10, 9, 13, 59, 30, 31, DateTimeKind.Local).AddTicks(6063),
                            FirstName = "Jongokhaya",
                            LastName = "Khwili"
                        },
                        new
                        {
                            Id = 10L,
                            CentreId = 3L,
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 31, DateTimeKind.Local).AddTicks(6065),
                            DoB = new DateTime(1989, 10, 9, 13, 59, 30, 31, DateTimeKind.Local).AddTicks(6066),
                            FirstName = "Thandeka",
                            LastName = "Khehle"
                        });
                });

            modelBuilder.Entity("Ameriolize_Aegis.Models.Period", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Periods");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 31, DateTimeKind.Local).AddTicks(7080),
                            Name = "Term 1"
                        },
                        new
                        {
                            Id = 2L,
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 31, DateTimeKind.Local).AddTicks(8285),
                            Name = "Term 2"
                        },
                        new
                        {
                            Id = 3L,
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 31, DateTimeKind.Local).AddTicks(8316),
                            Name = "Term 3"
                        },
                        new
                        {
                            Id = 4L,
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 31, DateTimeKind.Local).AddTicks(8319),
                            Name = "Term 4"
                        });
                });

            modelBuilder.Entity("Ameriolize_Aegis.Models.ProgramCentre", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CentreId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("ProgramId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CentreId");

                    b.HasIndex("ProgramId");

                    b.ToTable("Pro_Centres");
                });

            modelBuilder.Entity("Ameriolize_Aegis.Models.ProgramEnrollment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("PupilId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PupilId");

                    b.ToTable("Pro_Enrollments");
                });

            modelBuilder.Entity("Ameriolize_Aegis.Models.Programme", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CentreId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CentreId");

                    b.ToTable("Programs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CentreId = 1L,
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 32, DateTimeKind.Local).AddTicks(7198),
                            Name = "Literacy Development"
                        },
                        new
                        {
                            Id = 2L,
                            CentreId = 2L,
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 32, DateTimeKind.Local).AddTicks(8794),
                            Name = "Math And Science"
                        },
                        new
                        {
                            Id = 3L,
                            CentreId = 1L,
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 32, DateTimeKind.Local).AddTicks(8837),
                            Name = "Song And Music"
                        },
                        new
                        {
                            Id = 4L,
                            CentreId = 1L,
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 32, DateTimeKind.Local).AddTicks(8840),
                            Name = "Art And Music"
                        },
                        new
                        {
                            Id = 5L,
                            CentreId = 3L,
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 32, DateTimeKind.Local).AddTicks(8841),
                            Name = "Language And Speech"
                        });
                });

            modelBuilder.Entity("Ameriolize_Aegis.Models.ProgressReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Mark")
                        .HasColumnType("float");

                    b.Property<long>("PeriodId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProgramId")
                        .HasColumnType("bigint");

                    b.Property<long>("PupilId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("PupilId");

                    b.HasIndex("TeacherId");

                    b.ToTable("ProgressReports");
                });

            modelBuilder.Entity("Ameriolize_Aegis.Models.Pupil", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CentreId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TeacherId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CentreId");

                    b.HasIndex("ParentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Pupils");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CentreId = 1L,
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 32, DateTimeKind.Local).AddTicks(2950),
                            DoB = new DateTime(2016, 10, 9, 13, 59, 30, 32, DateTimeKind.Local).AddTicks(4426),
                            FirstName = "Peter",
                            LastName = "Pope",
                            ParentId = 1L,
                            TeacherId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CentreId = 2L,
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 32, DateTimeKind.Local).AddTicks(5993),
                            DoB = new DateTime(2017, 10, 9, 13, 59, 30, 32, DateTimeKind.Local).AddTicks(6048),
                            FirstName = "Amahle",
                            LastName = "Qweba",
                            ParentId = 2L,
                            TeacherId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            CentreId = 3L,
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 32, DateTimeKind.Local).AddTicks(6082),
                            DoB = new DateTime(2016, 10, 9, 13, 59, 30, 32, DateTimeKind.Local).AddTicks(6084),
                            FirstName = "Junior",
                            LastName = "Doe",
                            ParentId = 3L,
                            TeacherId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            CentreId = 2L,
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 32, DateTimeKind.Local).AddTicks(6087),
                            DoB = new DateTime(2017, 10, 9, 13, 59, 30, 32, DateTimeKind.Local).AddTicks(6091),
                            FirstName = "Jerry",
                            LastName = "Doe",
                            ParentId = 4L,
                            TeacherId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            CentreId = 1L,
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 32, DateTimeKind.Local).AddTicks(6094),
                            DoB = new DateTime(2015, 10, 9, 13, 59, 30, 32, DateTimeKind.Local).AddTicks(6095),
                            FirstName = "JJ",
                            LastName = "Doe",
                            ParentId = 5L,
                            TeacherId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            CentreId = 3L,
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 32, DateTimeKind.Local).AddTicks(6097),
                            DoB = new DateTime(2017, 10, 9, 13, 59, 30, 32, DateTimeKind.Local).AddTicks(6099),
                            FirstName = "Mihle",
                            LastName = "Newton",
                            ParentId = 6L,
                            TeacherId = 1L
                        },
                        new
                        {
                            Id = 7L,
                            CentreId = 2L,
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 32, DateTimeKind.Local).AddTicks(6189),
                            DoB = new DateTime(2016, 10, 9, 13, 59, 30, 32, DateTimeKind.Local).AddTicks(6192),
                            FirstName = "Sinazo",
                            LastName = "Qweba",
                            ParentId = 7L,
                            TeacherId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            CentreId = 3L,
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 32, DateTimeKind.Local).AddTicks(6195),
                            DoB = new DateTime(2015, 10, 9, 13, 59, 30, 32, DateTimeKind.Local).AddTicks(6196),
                            FirstName = "Buhle",
                            LastName = "Soze",
                            ParentId = 8L,
                            TeacherId = 1L
                        },
                        new
                        {
                            Id = 9L,
                            CentreId = 1L,
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 32, DateTimeKind.Local).AddTicks(6198),
                            DoB = new DateTime(2017, 10, 9, 13, 59, 30, 32, DateTimeKind.Local).AddTicks(6200),
                            FirstName = "Khaya",
                            LastName = "Khwili",
                            ParentId = 9L,
                            TeacherId = 1L
                        },
                        new
                        {
                            Id = 10L,
                            CentreId = 3L,
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 32, DateTimeKind.Local).AddTicks(6202),
                            DoB = new DateTime(2016, 10, 9, 13, 59, 30, 32, DateTimeKind.Local).AddTicks(6203),
                            FirstName = "Kubeka",
                            LastName = "Khehle",
                            ParentId = 10L,
                            TeacherId = 1L
                        });
                });

            modelBuilder.Entity("Ameriolize_Aegis.Models.Teacher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualification")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationTime = new DateTime(2021, 10, 9, 13, 59, 30, 31, DateTimeKind.Local).AddTicks(9661),
                            DoB = new DateTime(1976, 10, 9, 13, 59, 30, 32, DateTimeKind.Local).AddTicks(1201),
                            FirstName = "Margaret",
                            LastName = "Van Hum",
                            Qualification = "Bachelor Of Education In Child Development"
                        });
                });

            modelBuilder.Entity("Ameriolize_Aegis.Models.Attendance", b =>
                {
                    b.HasOne("Ameriolize_Aegis.Models.Pupil", "Pupil")
                        .WithMany()
                        .HasForeignKey("PupilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ameriolize_Aegis.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ameriolize_Aegis.Models.LessonPlan", b =>
                {
                    b.HasOne("Ameriolize_Aegis.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ameriolize_Aegis.Models.Parent", b =>
                {
                    b.HasOne("Ameriolize_Aegis.Models.Centre", "Centre")
                        .WithMany()
                        .HasForeignKey("CentreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ameriolize_Aegis.Models.ProgramCentre", b =>
                {
                    b.HasOne("Ameriolize_Aegis.Models.Centre", "Centre")
                        .WithMany()
                        .HasForeignKey("CentreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ameriolize_Aegis.Models.Programme", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ameriolize_Aegis.Models.ProgramEnrollment", b =>
                {
                    b.HasOne("Ameriolize_Aegis.Models.Pupil", "Pupil")
                        .WithMany("Enrollments")
                        .HasForeignKey("PupilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ameriolize_Aegis.Models.Programme", b =>
                {
                    b.HasOne("Ameriolize_Aegis.Models.Centre", "Centre")
                        .WithMany()
                        .HasForeignKey("CentreId");
                });

            modelBuilder.Entity("Ameriolize_Aegis.Models.ProgressReport", b =>
                {
                    b.HasOne("Ameriolize_Aegis.Models.Period", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ameriolize_Aegis.Models.Programme", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ameriolize_Aegis.Models.Pupil", "Pupil")
                        .WithMany("Reports")
                        .HasForeignKey("PupilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ameriolize_Aegis.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ameriolize_Aegis.Models.Pupil", b =>
                {
                    b.HasOne("Ameriolize_Aegis.Models.Centre", "Centre")
                        .WithMany()
                        .HasForeignKey("CentreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ameriolize_Aegis.Models.Parent", "Parent")
                        .WithMany("Pupils")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ameriolize_Aegis.Models.Teacher", "Teacher")
                        .WithMany("Pupils")
                        .HasForeignKey("TeacherId");
                });
#pragma warning restore 612, 618
        }
    }
}
